name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  ngnix-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Clonning repo
      uses: actions/checkout@v3
    
    - name: Build and push the nginx image
      run: |
        ls
        TAG=$(date +%s)
        docker build ./nginx --file Dockerfile.ecs.dev --tag ${{ secrets.DOCKER_USERNAME }}/nginx:$TAG --tag ${{ secrets.DOCKER_USERNAME }}/nginx:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx:$TAG
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest

    - 
      name: Build the server image
      run: |
        TAG=$(date +%s)
        docker build ./server --tag ${{ secrets.DOCKER_USERNAME }}/server:$TAG --tag ${{ secrets.DOCKER_USERNAME }}/server:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/server:$TAG
        docker push ${{ secrets.DOCKER_USERNAME }}/server:latest

    - name: Build the frontend image
      run: |
        TAG=$(date +%s)
        docker build ./client --tag ${{ secrets.DOCKER_USERNAME }}/frontend:$TAG --tag ${{ secrets.DOCKER_USERNAME }}/frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:$TAG
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest 
    